name: Ingest and Build

on:
  push:
    paths:
      - 'data/**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingest
        run: |
          python scripts/ingest.py --input data/my_study_data.csv --out docs --citation "Add your citation here" --license "CC-BY 4.0" --doi "10.5281/zenodo.xxxx" --contact "data-owner@example.edu"

      - name: Commit generated docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/data.json docs/columns.json docs/metadata.json
          git commit -m "Auto-update generated docs (ingest)" || echo "no changes to commit"
          git push
        env:
          # The default GITHUB_TOKEN allows write by Actions to the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
